import type {Metadata} from "next";
import "./globals.css";
import "@/shared/styles/main.css"
import {Nunito} from "next/font/google";
import {Footer, Header} from "@/shared/components";

const nunito = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['500', '600', '700'],
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="ru">
        <body className={nunito.variable}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
